"""empty message

Revision ID: 2b671dc0e4fc
Revises: 946a1cd19559
Create Date: 2021-08-28 10:27:06.054585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b671dc0e4fc'
down_revision = '946a1cd19559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('participants_name_key', 'participants', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('participants_name_key', 'participants', ['name'])
    # ### end Alembic commands ###
