"""empty message

Revision ID: 47387e536227
Revises: b25e4338c941
Create Date: 2021-08-31 10:10:32.860015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47387e536227'
down_revision = 'b25e4338c941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guest_event', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('guest_event', 'guest_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('guest_event', 'id')
    op.alter_column('participant_event', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('participant_event', 'participant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('participant_event', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant_event', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('participant_event', 'participant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('participant_event', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('guest_event', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('guest_event', 'guest_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('guest_event', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
