"""empty message

Revision ID: 66f2d4364cf2
Revises: f0c383d6c47e
Create Date: 2021-08-24 10:38:20.528007

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '66f2d4364cf2'
down_revision = 'f0c383d6c47e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('description', sa.String(length=512), nullable=True))
    op.add_column('events', sa.Column('end', sa.DateTime(), nullable=True))
    op.add_column('events', sa.Column('start', sa.DateTime(), nullable=True))
    op.drop_column('events', 'datetime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('events', 'start')
    op.drop_column('events', 'end')
    op.drop_column('events', 'description')
    # ### end Alembic commands ###
